# Generated by Django 4.2.29 on 2026-03-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('axiom', 'Аксиома'), ('theorem', 'Теорема')], max_length=10)),
                ('level', models.PositiveIntegerField(help_text='0 — аксиома, 1..N — теорема (чем больше, тем сложнее)')),
                ('description', models.TextField(help_text='Markdown-текст с доказательством. Математика в формате $...$ и $$...$$')),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='graph.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='graph.node')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
